#!/usr/bin/env python3
"""
NetDoctor – Report Generator
Generates text and simple HTML reports.
Pure standard library only.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List


REPORTS_DIR = Path("reports_output")


def _ensure_reports_dir() -> None:
    REPORTS_DIR.mkdir(exist_ok=True)


def generate_text_report(data: Dict[str, Any]) -> str:
    """Generate a clean plain-text report."""
    target = data.get("target", "Unknown")
    health = data.get("health", {})
    checks = data.get("checks", [])

    lines = [
        "=" * 60,
        f"  NetDoctor Report – {target}",
        f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "=" * 60,
        "",
        f"  Health Score : {health.get('score', 'N/A')}/100",
        f"  Grade        : {health.get('grade', 'N/A')} ({health.get('label', '')})",
        "",
        "-" * 60,
        "  Checks:",
        "-" * 60,
    ]

    for check in checks:
        status = "PASS" if check.get("success") else "FAIL"
        latency = f"{check['latency_ms']:.1f} ms" if check.get("latency_ms") is not None else "-"
        lines.append(f"  [{status}] {check.get('name', ''):<12} {check.get('detail', '')} ({latency})")
        if check.get("diagnosis"):
            lines.append(f"         → {check['diagnosis']}")

    if health.get("notes"):
        lines.append("")
        lines.append("-" * 60)
        lines.append("  Notes:")
        for note in health["notes"]:
            lines.append(f"  • {note}")

    lines.append("")
    lines.append("=" * 60)
    return "\n".join(lines)


def generate_html_report(data: Dict[str, Any]) -> str:
    """Generate a simple self-contained HTML report."""
    target = data.get("target", "Unknown")
    health = data.get("health", {})
    checks = data.get("checks", [])
    score = health.get("score", 0)
    grade = health.get("grade", "?")

    # Simple color based on grade
    grade_color = {
        "A": "#16a34a",
        "B": "#65a30d",
        "C": "#ca8a04",
        "D": "#ea580c",
        "F": "#dc2626",
    }.get(grade, "#6b7280")

    rows = ""
    for check in checks:
        status = "✅" if check.get("success") else "❌"
        latency = f"{check['latency_ms']:.1f} ms" if check.get("latency_ms") is not None else "-"
        diagnosis = check.get("diagnosis", "")
        rows += f"""
        <tr>
            <td>{status}</td>
            <td><strong>{check.get('name', '')}</strong></td>
            <td>{check.get('detail', '')}</td>
            <td>{latency}</td>
            <td>{diagnosis}</td>
        </tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NetDoctor Report – {target}</title>
    <style>
        body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1f2937; }}
        h1 {{ margin-bottom: 5px; }}
        .score {{ font-size: 1.4rem; font-weight: 600; color: {grade_color}; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 24px; }}
        th, td {{ text-align: left; padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }}
        th {{ background: #f9fafb; }}
        .footer {{ margin-top: 40px; font-size: 0.85rem; color: #6b7280; }}
    </style>
</head>
<body>
    <h1>🩺 NetDoctor Report</h1>
    <p><strong>Target:</strong> {target}</p>
    <p class="score">Health Score: {score}/100 ({grade})</p>
    <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th>Check</th>
                <th>Detail</th>
                <th>Latency</th>
                <th>Diagnosis</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>

    <div class="footer">
        Generated by NetDoctor – Zero third-party dependencies
    </div>
</body>
</html>
"""
    return html


def save_report(data: Dict[str, Any], format: str = "text") -> str:
    """
    Save a report to disk.
    format: "text" or "html"
    Returns the path of the saved file.
    """
    _ensure_reports_dir()

    target = data.get("target", "report")
    safe_target = "".join(c if c.isalnum() or c in "-." else "_" for c in target)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    if format == "html":
        content = generate_html_report(data)
        filename = f"{timestamp}_{safe_target}.html"
    else:
        content = generate_text_report(data)
        filename = f"{timestamp}_{safe_target}.txt"

    filepath = REPORTS_DIR / filename
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return str(filepath)